---
version: '3.5'
networks:
  example.com:
    name: "example.com"
    driver: bridge
services:
  keeper01:
    image: clickhouse/clickhouse-keeper:latest
    ports:
      - "9181:9181"
      - "9182:9182"
    container_name: keeper01
    hostname: keeper01
    networks:
      example.com: {}
    volumes:
      - ./config/keeper01.xml:/etc/clickhouse-keeper/keeper_config.xml

  keeper02:
    image: clickhouse/clickhouse-keeper:latest
    container_name: keeper02
    hostname: keeper02
    networks:
      example.com: {}
    volumes:
      - ./config/keeper02.xml:/etc/clickhouse-keeper/keeper_config.xml

  keeper03:
    image: clickhouse/clickhouse-keeper:latest
    container_name: keeper03
    hostname: keeper03
    networks:
      example.com: {}
    volumes:
      - ./config/keeper03.xml:/etc/clickhouse-keeper/keeper_config.xml

  clickhouse01:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse01
    container_name: clickhouse01
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
    - "keeper01"
    - "keeper02"
    - "keeper03"
    ports:
      - "9001:9000"
    networks:
      example.com: {}
    volumes:
      - ./config/config01.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml

  clickhouse02:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse02
    container_name: clickhouse02
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
    - "keeper01"
    - "keeper02"
    - "keeper03"
    ports:
      - "9002:9000"
    networks:
      example.com: {}
    volumes:
      - ./config/config02.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml

  clickhouse03:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse03
    container_name: clickhouse03
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
    - "keeper01"
    - "keeper02"
    - "keeper03"
    ports:
      - "9003:9000"
    networks:
      example.com: {}
    volumes:
      - ./config/config03.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml

  clickhouse04:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse04
    container_name: clickhouse04
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
    - "keeper01"
    - "keeper02"
    - "keeper03"
    ports:
      - "9004:9000"
    networks:
      example.com: {}
    volumes:
      - ./config/config04.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml

  clickhouse05:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse05
    container_name: clickhouse05
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
    - "keeper01"
    - "keeper02"
    - "keeper03"
    ports:
      - "9005:9000"
    networks:
      example.com: {}
    volumes:
      - ./config/config05.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml

  clickhouse06:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse06
    container_name: clickhouse06
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
    - "keeper01"
    - "keeper02"
    - "keeper03"
    ports:
      - "9006:9000"
    networks:
      example.com: {}
    volumes:
      - ./config/config06.xml:/etc/clickhouse-server/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
