apiVersion: 1

deleteDatasources:
  - name: Clickhouse
    orgId: 1

datasources:
- name: Clickhouse
  type: grafana-clickhouse-datasource
  orgId: 1
  isDefault: true
  jsonData:
     defaultDatabase: default
     port: 9000
     host: clickhouse01
     username: default
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: true
