---
version: '3.8'
networks:
  example.com:
    name: example.com
    driver: bridge
services:
  keeper01:
    image: clickhouse/clickhouse-keeper:head-alpine
    ports:
    - 9181:9181
    container_name: keeper01
    hostname: keeper01
    networks:
      example.com: {}
    volumes:
    - ./config/keeper01/keeper.xml:/etc/clickhouse-keeper/keeper_config.xml
    - ./log/keeper01:/var/log/clickhouse-keeper
    - ./data/keeper01:/var/lib/clickhouse
  keeper02:
    image: clickhouse/clickhouse-keeper:head-alpine
    ports:
    - 9182:9181
    container_name: keeper02
    hostname: keeper02
    networks:
      example.com: {}
    volumes:
    - ./config/keeper02/keeper.xml:/etc/clickhouse-keeper/keeper_config.xml
    - ./log/keeper02:/var/log/clickhouse-keeper
    - ./data/keeper02:/var/lib/clickhouse
  keeper03:
    image: clickhouse/clickhouse-keeper:head-alpine
    ports:
    - 9183:9181
    container_name: keeper03
    hostname: keeper03
    networks:
      example.com: {}
    volumes:
    - ./config/keeper03/keeper.xml:/etc/clickhouse-keeper/keeper_config.xml
    - ./log/keeper03:/var/log/clickhouse-keeper
    - ./data/keeper03:/var/lib/clickhouse
  clickhouse01:
    image: clickhouse/clickhouse-server:head-alpine
    hostname: clickhouse01
    container_name: clickhouse01
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
    - 9001:9000
    - 8123:8123
    networks:
      example.com: {}
    volumes:
    - ./config/clickhouse01:/etc/clickhouse-server/config.d
    - ./config/users.xml:/etc/clickhouse-server/users.d/users.xml
    - ./data/clickhouse01:/var/lib/clickhouse
    - ./log/clickhouse01:/var/log/clickhouse-server
  clickhouse02:
    image: clickhouse/clickhouse-server:head-alpine
    hostname: clickhouse02
    container_name: clickhouse02
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
    - 9002:9000
    - 8124:8123
    networks:
      example.com: {}
    volumes:
    - ./config/clickhouse02:/etc/clickhouse-server/config.d
    - ./config/users.xml:/etc/clickhouse-server/users.d/users.xml
    - ./data/clickhouse02:/var/lib/clickhouse
    - ./log/clickhouse02:/var/log/clickhouse-server
  minio:
    image: quay.io/minio/minio
    hostname: minio
    container_name: minio
    ports:
      - "8000:8000"
      - "8001:8001"
    command: server --address 0.0.0.0:8000 --console-address 0.0.0.0:8001 /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    networks:
      example.com: {}
  create-buckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        /usr/bin/mc config host add myminio http://minio:8000 minio minio123;
        /usr/bin/mc admin info myminio;
        /usr/bin/mc mb myminio/mys3bucket;
        /usr/bin/mc policy set public myminio/mys3bucket;
        exit 0;
      "
    networks:
      example.com: {}
