---
version: '3.7'
networks:
  example.com:
    name: "example.com"
    driver: bridge
services:
  clickhouse01:
    image: clickhouse/clickhouse-server:23.3.2.37-alpine
    hostname: clickhouse01
    container_name: clickhouse01
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9001:9000"
      - "9181:9181"
      - "8123:8123"
    networks:
      example.com: {}
    volumes:
      - ./config/clickhouse01/config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse01/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./config/users/users.xml:/etc/clickhouse-server/users.xml
      - ./data/clickhouse01:/var/lib/clickhouse
      - ./log/clickhouse01:/var/log/clickhouse-server

