---
version: '3.8'
networks:
  example.com:
    name: "example.com"
    driver: bridge
services:
  keeper:
    image: clickhouse/clickhouse-keeper:latest
    ports:
      - "9181:9181"  
    container_name: keeper
    hostname: keeper
    networks:
      example.com: {}
    volumes:
      - ./config/keeper/keeper.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ./data/keeper:/var/lib/clickhouse
      - ./log/keeper:/var/log/clickhouse-keeper

  clickhouse:
    image: clickhouse/clickhouse-server:head-alpine
    hostname: clickhouse
    container_name: clickhouse
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9001:9000"
    networks:
      example.com: {}
    volumes:
      - ./config/clickhouse:/etc/clickhouse-server/config.d
      - ./config/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./data/clickhouse:/var/lib/clickhouse
      - ./log/clickhouse:/var/log/clickhouse-server

