---
version: '3.7'
networks:
  example.com:
    name: "example.com"
    driver: bridge
services:
  clickhouse01:
    image: clickhouse/clickhouse-server:23.3.2.37-alpine
    hostname: clickhouse01
    container_name: clickhouse01
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9441:9440"
      - "9281:9281"
      - "8443:8443"
    networks:
      example.com: {}
    volumes:
      - ./config/clickhouse01/config01.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse01/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./config/users/users.xml:/etc/clickhouse-server/users.xml
      - ./data/clickhouse01:/var/lib/clickhouse
      - ./certs:/etc/clickhouse-server/certs
      - ./log/clickhouse01:/var/log/clickhouse-server
      - ./config/client.xml:/etc/clickhouse-client/config.xml

  clickhouse02:
    image: clickhouse/clickhouse-server:23.3.2.37-alpine
    hostname: clickhouse02
    container_name: clickhouse02
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9442:9440"
      - "9282:9281"
    networks:
      example.com: {}
    volumes:
      - ./config/clickhouse02/config02.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse02/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./config/users/users.xml:/etc/clickhouse-server/users.xml
      - ./data/clickhouse02:/var/lib/clickhouse
      - ./certs:/etc/clickhouse-server/certs
      - ./log/clickhouse02:/var/log/clickhouse-server
      - ./config/client.xml:/etc/clickhouse-client/config.xml

  clickhouse03:
    image: clickhouse/clickhouse-server:23.3.2.37-alpine
    hostname: clickhouse03
    container_name: clickhouse03
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9443:9440"
      - "9283:9281"
    networks:
      example.com: {}
    volumes:
      - ./config/clickhouse03/config03.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse03/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./config/users/users.xml:/etc/clickhouse-server/users.xml
      - ./data/clickhouse03:/var/lib/clickhouse
      - ./certs:/etc/clickhouse-server/certs
      - ./log/clickhouse03:/var/log/clickhouse-server
      - ./config/client.xml:/etc/clickhouse-client/config.xml

  clickhouse04:
    image: clickhouse/clickhouse-server:23.3.2.37-alpine
    hostname: clickhouse04
    container_name: clickhouse04
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9444:9440"
      - "9284:9281"
    networks:
      example.com: {}
    volumes:
      - ./config/clickhouse04/config04.xml:/etc/clickhouse-server/config.xml
      - ./config/users/users.xml:/etc/clickhouse-server/users.xml
      - ./data/clickhouse04:/var/lib/clickhouse
      - ./certs:/etc/clickhouse-server/certs
      - ./log/clickhouse04:/var/log/clickhouse-server
      - ./config/client.xml:/etc/clickhouse-client/config.xml

