---
version: '3.7'
networks:
  example.com:
    name: "example.com"
    driver: bridge
services:
  clickhouse01:
    image: clickhouse/clickhouse-server:23.3.2.37-alpine
    hostname: clickhouse01
    container_name: clickhouse01
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9001:9000"
      - "9181:9181"
      - "8123:8123"
    networks:
      example.com: {}
    volumes:
      - ./config/clickhouse01/config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse01/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./config/users/users.xml:/etc/clickhouse-server/users.xml
      - ./data/clickhouse01:/var/lib/clickhouse
      - ./log/clickhouse01:/var/log/clickhouse-server

  clickhouse02:
    image: clickhouse/clickhouse-server:23.3.2.37-alpine
    hostname: clickhouse02
    container_name: clickhouse02
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9002:9000"
      - "9182:9181"
    networks:
      example.com: {}
    volumes:
      - ./config/clickhouse02/config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse02/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./config/users/users.xml:/etc/clickhouse-server/users.xml
      - ./data/clickhouse02:/var/lib/clickhouse
      - ./log/clickhouse02:/var/log/clickhouse-server

  clickhouse03:
    image: clickhouse/clickhouse-server:23.3.2.37-alpine
    hostname: clickhouse03
    container_name: clickhouse03
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9003:9000"
      - "9183:9181"
    networks:
      example.com: {}
    volumes:
      - ./config/clickhouse03/config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse03/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./config/users/users.xml:/etc/clickhouse-server/users.xml
      - ./data/clickhouse03:/var/lib/clickhouse
      - ./log/clickhouse03:/var/log/clickhouse-server

  clickhouse04:
    image: clickhouse/clickhouse-server:23.3.2.37-alpine
    hostname: clickhouse04
    container_name: clickhouse04
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9444:9440"
      - "9284:9281"
    networks:
      example.com: {}
    volumes:
      - ./config/clickhouse04/config.xml:/etc/clickhouse-server/config.xml
      - ./config/users/users.xml:/etc/clickhouse-server/users.xml
      - ./data/clickhouse04:/var/lib/clickhouse
      - ./log/clickhouse04:/var/log/clickhouse-server

  mysql:
    image: mysql:8.0.32
    hostname: mysql
    container_name: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=rootpass
     - MYSQL_DATABASE=mysqldb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      example.com: {}
