---
version: '3.8'
networks:
  example.com:
    name: "example.com"
    driver: bridge
services:
  clickhouse01:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse01
    container_name: clickhouse01
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9001:9000"
    networks:
      example.com: {}
    volumes:
      - ./config/server/config01.xml:/etc/clickhouse-server/config.d/config.xml
      - ./config/server/keeper01.xml:/etc/clickhouse-server/config.d/keeper-config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./data/clickhouse01:/var/lib/clickhouse

  clickhouse02:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse02
    container_name: clickhouse02
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9002:9000"
    networks:
      example.com: {}
    volumes:
      - ./config/server/config02.xml:/etc/clickhouse-server/config.d/config.xml
      - ./config/server/keeper02.xml:/etc/clickhouse-server/config.d/keeper-config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./data/clickhouse02:/var/lib/clickhouse

  clickhouse03:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse03
    container_name: clickhouse03
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9003:9000"
    networks:
      example.com: {}
    volumes:
      - ./config/server/config03.xml:/etc/clickhouse-server/config.d/config.xml
      - ./config/server/keeper03.xml:/etc/clickhouse-server/config.d/keeper-config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./data/clickhouse03:/var/lib/clickhouse

  clickhouse04:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse04
    container_name: clickhouse04
    cpus: 0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9004:9000"
    networks:
      example.com: {}
    volumes:
      - ./config/server/config04.xml:/etc/clickhouse-server/config.d/config.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./data/clickhouse04:/var/lib/clickhouse

