---
version: '3.8'
networks:
  example.com:
    name: "example.com"
    driver: bridge
services:
  mysql:
    image: mysql:8.0.32
    hostname: mysql
    container_name: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=rootpass
     - MYSQL_DATABASE=mysqldb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      example.com: {}
