---
version: '3.8'
networks:
  example.com:
    name: "example.com"
    driver: bridge
services:
  minio:
    image: quay.io/minio/minio
    hostname: minio
    container_name: minio
    ports:
      - "8000:8000"
      - "8001:8001"
    command: server --address 0.0.0.0:8000 --console-address 0.0.0.0:8001 /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    networks:
      example.com: {}
  create-buckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        /usr/bin/mc config host add myminio http://minio:8000 minio minio123;
        /usr/bin/mc admin info myminio;
        /usr/bin/mc mb myminio/mys3bucket;
        /usr/bin/mc policy set public myminio/mys3bucket;
        exit 0;
      "
    networks:
      example.com: {}
